version: "3.8"

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    command: air ./main.go -b 0.0.0.0
    networks:
      - forum
    links:
      - "db:database"
  db:
    image: postgres:alpine
    environment:
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
      - DB_DRIVER=${DB_DRIVER}
      - PGPORT=${PGPORT}
      - PGHOST=${PGHOST}
      - PORT=${PORT}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - forum
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - forum

volumes:
  postgres-db:

networks:
  forum:
    driver: bridge
